spring:
  # ???????
  datasource:
    # ???????
    type:
    # ?????????
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ??????8.0.27 5??????? jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf-8&useSSL=false
    url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

    # ??????
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
